### ISSUE TITLE
Relax matplotlib requirement for easier installation

### ISSUE THREAD

**Issue by jonrkarr** [SBRG/MASSpy#157]
matplotlib 3.2 has extra requirements for libfreetype6-dev. If possible, it would be helpful to relax this to something like `matplotlib >= 3.2`.

**Comment by z-haiman** [comment]
There is a specific function in matplotlib (rc.validate_legend_loc) that gets deprecated. Once removed, the requirement can be relaxed. 

Line 571

https://github.com/SBRG/MASSpy/blob/1288834750a92f765cb6d97e16b28af7c9ba088a/mass/visualization/visualization_util.py#L366

I have it removed in the 0.2.0 version that's being developed currently

**Comment by jonrkarr** [comment]
I wasn't sure if MASSpy requires a specific version.

Alternatively, could you make matplotlib an optional requirement similar to Escher?

**Comment by z-haiman** [comment]
Definitely, I can make that happen in the 0.2.0 version.

Also, feel free to reach out to me too if there is anything specific you are looking to accomplish

**Comment by z-haiman** [comment]
@jonrkarr I believe I found a way to make the install for matplotlib optional. Let me know if this works for you

**Comment by jonrkarr** [comment]
That would be a helpful solution. `setuptools.setup` has an argument for optional dependencies.

**Comment by z-haiman** [comment]
Relaxed the requirement/made it optional, let me know if it works!

**Comment by jonrkarr** [comment]
The revised dependencies is great. This makes it easier to create a single Python environment with many simulation tools, which is helpful to a few groups.

**Comment by jonrkarr** [comment]
This is already working with 0.1.5.

**Comment by z-haiman** [comment]
Awesome, I'll close this issue then!
